project_id = "xdlowvfzhvjzbtgvurzj"

[functions.check-user-exists]
verify_jwt = false

[functions.send-invitation-email]
verify_jwt = false

[functions.send-subscription-email]
verify_jwt = false

[functions.send-support-email]
verify_jwt = false

[functions.send-incident-email]
verify_jwt = false
